{
  "swagger": "2.0",
  "info": {
    "title": "ChapRoom API",
    "description": "Chaproom Backend Restful-API",
    "version": "1.0"
  },
  "host": "localhost:3000",
  "basePath": "/v1",
  "schemes": ["http", "https"],
  "paths": {
    "/users/auth/register": {
      "post": {
        "tags": ["Users Auth ( Login & Register & ... )"],
        "summary": "Send confirmation code for Register new user",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersRegister" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "isSuccess": true,
                  "message": "کد ارسال شد",
                  "phoneNumber": "09385667274",
                  "expireAt": "2022-10-17T20:31:30.629Z"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": " این اکانت قبلا ساخته شده بود ",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/auth/register/confirm": {
      "post": {
        "tags": ["Users Auth ( Login & Register & ... )"],
        "summary": "confirm your code and Register new user",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersRegisterConfirm" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "marketingBalance": 0,
                  "balance": 0,
                  "active": true,
                  "id": 1,
                  "phoneNumber": "09385667274",
                  "name": "Programmer Kasra",
                  "password": "This Is A Passowrd!",
                  "updatedAt": "2022-10-06T18:17:07.510Z",
                  "createdAt": "2022-10-06T18:17:07.510Z"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": " این اکانت قبلا ساخته شده بود ",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/auth/login": {
      "post": {
        "tags": ["Users Auth ( Login & Register & ... )"],
        "summary": "Login exist user",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersLogin" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "Programmer Kasra",
                  "phoneNumber": "09385667274",
                  "marketingBalance": 0,
                  "balance": 0,
                  "createdAt": "2022-10-12T10:48:45.000Z",
                  "updatedAt": "2022-10-14T19:21:59.000Z",
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmUiOiIwOTM4NTY2NzI3NCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NjYwMDIxODYsImV4cCI6MTY2OTYwMjE4Nn0.BsYeOciUA1uMfAvx3agupXAWTnYUqldo39tNmSyPHUQ"
                  }
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "نام کاربری یا رمزعبور اشتباه میباشد",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/profile/dashboard": {
      "get": {
        "tags": ["Users Profile"],
        "summary": "get dashboard",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 24,
                  "name": "Programmer Kasra",
                  "phoneNumber": "09385667274",
                  "marketingBalance": 0,
                  "balance": 10000,
                  "active": true,
                  "createdAt": "2022-10-19T21:33:07.000Z",
                  "updatedAt": "2022-10-19T22:36:39.000Z",
                  "deletedAt": null,
                  "walletBalance": 10000,
                  "orders": [
                    {
                      "id": 3,
                      "status": "pending",
                      "amount": 15000,
                      "createdAt": "2022-10-19T22:34:30.000Z",
                      "updatedAt": "2022-10-19T22:36:39.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/profile": {
      "put": {
        "tags": ["Users Profile"],
        "summary": "Change Profile Information ( password & name )",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersProfile" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "name": [" نام اشتباه وارد شده است است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "رمزعبور نا امن میباشد",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users Profile"],
        "summary": "Get user profile",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "Programmer Kasra",
                  "phoneNumber": "09385667274",
                  "marketingBalance": 0,
                  "balance": 0,
                  "createdAt": "2022-10-12T10:48:45.000Z",
                  "updatedAt": "2022-10-14T19:21:59.000Z",
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmUiOiIwOTM4NTY2NzI3NCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NjYwMDIxODYsImV4cCI6MTY2OTYwMjE4Nn0.BsYeOciUA1uMfAvx3agupXAWTnYUqldo39tNmSyPHUQ"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "در گرفتن اطلاعات دچار مشکل شدیم",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/files": {
      "post": {
        "tags": ["Users Files"],
        "summary": "Upload new file",
        "consumes": ["multipart/form-data"],
        "produces": ["multipart/form-data"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "formData",
            "name": "attachment",
            "type": "file",
            "required": true
          }
        ]
      }
    },
    "/users/folders": {
      "post": {
        "tags": ["Users Folders"],
        "summary": "create new folder",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersFolders" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "id": 1,
                  "color": "رنگی",
                  "side": "تک رو",
                  "size": "A4",
                  "countOfPages": 8,
                  "uploadedPages": 6,
                  "binding": "من صحافی میخواهم",
                  "numberOfCopies": 5,
                  "description": "این یک توضیح است",
                  "shipmentPrice": "5000",
                  "amount": "5000",
                  "files": [{ "id": 1 }]
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "size": ["سایز صفحه مشخص نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users Folders"],
        "summary": "get open folders",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "color": "رنگی",
                  "side": "تک رو",
                  "size": "A4",
                  "countOfPages": 8,
                  "uploadedPages": 6,
                  "binding": "من صحافی میخواهم",
                  "numberOfCopies": 5,
                  "description": "این یک توضیح است",
                  "shipmentPrice": "5000",
                  "amount": "5000",
                  "files": [
                    {
                      "id": 1,
                      "uploadedFileName": "CV-4.pdf",
                      "fileName": "CV-4.pdf",
                      "fileUrl": "are",
                      "pageCount": 1,
                      "createdAt": "2022-10-12T10:51:37.000Z",
                      "updatedAt": "2022-10-12T10:51:37.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "size": ["سایز صفحه مشخص نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/wallets/deposit": {
      "post": {
        "tags": ["Users Wallet"],
        "summary": "create new deposit payment url for increase wallet balance",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersDeposit" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "paymentUrl": "https://sandbox.zarinpal.com/pg/StartPay/000000000000000000000000000000956163",
                  "amount": 1000
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "amount": ["مبلغ نادرست"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/folders/id/{id}": {
      "put": {
        "tags": ["Users Folders"],
        "summary": "edit exist folder",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersFolders" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "color": "رنگی",
                  "side": "تک رو",
                  "size": "A4",
                  "countOfPages": 8,
                  "uploadedPages": 6,
                  "binding": "من صحافی میخواهم",
                  "numberOfCopies": 5,
                  "description": "این یک توضیح است",
                  "shipmentPrice": 5000,
                  "amount": 5000,
                  "files": [
                    {
                      "id": 1,
                      "uploadedFileName": "CV-4.pdf",
                      "fileName": "CV-4.pdf",
                      "fileUrl": "are",
                      "pageCount": 1,
                      "createdAt": "2022-10-12T10:51:37.000Z",
                      "updatedAt": "2022-10-12T10:51:37.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "size": ["سایز صفحه مشخص نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users Folders"],
        "summary": "get single open folder",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersFolders" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "color": "رنگی",
                  "side": "تک رو",
                  "size": "A4",
                  "countOfPages": 8,
                  "uploadedPages": 6,
                  "binding": "من صحافی میخواهم",
                  "numberOfCopies": 5,
                  "description": "این یک توضیح است",
                  "shipmentPrice": 5000,
                  "price": 5000,
                  "files": [{ "id": 1 }]
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "size": ["سایز صفحه مشخص نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Users Folders"],
        "summary": "delete single  folder",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "color": "رنگی",
                  "side": "تک رو",
                  "size": "A4",
                  "countOfPages": 8,
                  "uploadedPages": 6,
                  "binding": "من صحافی میخواهم",
                  "numberOfCopies": 5,
                  "description": "این یک توضیح است",
                  "shipmentPrice": 5000,
                  "price": 5000,
                  "files": [{ "id": 1 }]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکلی پیش آمده است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/addresses": {
      "post": {
        "tags": ["Users Addresses"],
        "summary": "Add new address",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersAddresses" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "id": 1,
                  "recipientName": "کسری تحویل میگیرم",
                  "recipientPhoneNumber": "09385667274",
                  "recipientPostalCode": "4675744151",
                  "recipientDeliveryProvince": "مازندران",
                  "recipientDeliveryCity": "ساری",
                  "recipientDeliveryAddress": "خیابان لاله کوچه بهار پلاک دوازده"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [
                    {
                      "recipientPhoneNumber": ["شماره تلفن مقصد نامعتبر است"]
                    },
                    {
                      "recipientDeliveryProvince": ["استان نامعتبر است"]
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این آدرس قبلا درج شده است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users Addresses"],
        "summary": "Get All addresses",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": [
                  {
                    "id": 1,
                    "recipientName": "کسری تحویل میگیرم",
                    "recipientPhoneNumber": "09385667274",
                    "recipientPostalCode": "4675744151",
                    "recipientDeliveryProvince": "مازندران",
                    "recipientDeliveryCity": "ساری",
                    "recipientDeliveryAddress": "خیابان لاله کوچه بهار پلاک دوازده"
                  },
                  {
                    "id": 2,
                    "recipientName": "رضا تحویل میگیرم",
                    "recipientPhoneNumber": "09385667276",
                    "recipientPostalCode": "4675744157",
                    "recipientDeliveryProvince": "مازندران",
                    "recipientDeliveryCity": "ساری",
                    "recipientDeliveryAddress": "خیابان لاله کوچه بهار پلاک یازده"
                  }
                ],
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "مشکل در فراخوانی داده ها",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/addresses/id/{id}": {
      "get": {
        "tags": ["Users Addresses"],
        "summary": "Get Single address",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "recipientName": "کسری تحویل میگیرم",
                  "recipientPhoneNumber": "09385667274",
                  "recipientPostalCode": "4675744151",
                  "recipientDeliveryProvince": "مازندران",
                  "recipientDeliveryCity": "ساری",
                  "recipientDeliveryAddress": "خیابان لاله کوچه بهار پلاک دوازده"
                },
                "error": null
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Users Addresses"],
        "summary": "Delete addresses",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت پاک شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "امکان پاک کردن این رکورد وجود ندارد",
                  "details": []
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Users Addresses"],
        "summary": "Update ( change ) address",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersAddresses" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [
                    {
                      "recipientPhoneNumber": ["شماره تلفن مقصد نامعتبر است"]
                    },
                    {
                      "recipientDeliveryProvince": ["استان نامعتبر است"]
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این داده قبلا درج شده بود",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/wallets/withdrawal": {
      "post": {
        "tags": ["Users Wallet"],
        "summary": "Add new withdrawal from user",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersWithdrawal" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [
                    {
                      "recipientPhoneNumber": ["شماره تلفن مقصد نامعتبر است"]
                    },
                    {
                      "recipientDeliveryProvince": ["استان نامعتبر است"]
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این داده قبلا درج شده بود",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/public/contact-us": {
      "post": {
        "tags": ["Public"],
        "summary": "create new contact-us message",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/ContactUs" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "id": 4,
                  "name": "Programmer Kasra",
                  "phoneNumber": "09385667274",
                  "message": "Hi,this is a message !"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "name": ["شماره تلفن مقصد نامعتبر است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/public/َaffiliates": {
      "post": {
        "tags": ["Public"],
        "summary": "create new affiliates message ( this request needed use in home page - Hamkari ba moasesat )",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/َAffiliates" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "id": 4,
                  "phoneNumber": "09385667274"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن نامعتبر است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/orders/id/{id}": {
      "get": {
        "tags": ["Users Orders"],
        "summary": "create new order",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 3,
                  "status": "pending",
                  "amount": 15000,
                  "sendMethod": "پست پیشتاز",
                  "postFee": null,
                  "recipientName": "کسری تحویل میگیره",
                  "recipientPhoneNumber": "09385667274",
                  "recipientPostalCode": "4675744151",
                  "recipientDeliveryProvince": "مازندران",
                  "recipientDeliveryCity": "ساری",
                  "recipientDeliveryAddress": "خیابان لاله کوچه بهار پلاک دوازده",
                  "discountCode": null,
                  "discountAmount": null,
                  "trackingNumber": null,
                  "notFinishingReason": null,
                  "walletPaidAmount": 0,
                  "gatewayPaidAmount": 10000,
                  "sentAt": null,
                  "createdAt": "2022-10-19T22:34:30.000Z",
                  "updatedAt": "2022-10-19T22:36:39.000Z",
                  "deletedAt": null,
                  "folders": [
                    {
                      "id": 1,
                      "color": "رنگی",
                      "side": "تک رو",
                      "size": "A4",
                      "countOfPages": 6,
                      "uploadedPages": 2,
                      "binding": "میخواهم صحافی بشود",
                      "numberOfCopies": 6,
                      "description": "این یک توضیح است",
                      "shipmentPrice": 20000,
                      "summary": "تست / تست / تست / تست / تست",
                      "countOfFiles": 1,
                      "filesUrl": "https://google.com",
                      "amount": 10000,
                      "telegramUploadFile": false,
                      "whatsappUploadFile": false,
                      "createdAt": "2022-10-19T21:55:07.000Z",
                      "updatedAt": "2022-10-19T21:55:07.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Users Orders"],
        "summary": "create new order",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UpdateUsersOrders" }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/orders": {
      "post": {
        "tags": ["Users Orders"],
        "summary": "create new order",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UsersOrders" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 4,
                  "phoneNumber": "09385667274"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users Orders"],
        "summary": "find all orders",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 0,
                  "pageSize": 25,
                  "totalCount": 1,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "data": [
                    {
                      "id": 3,
                      "status": "pending",
                      "notFinishingReason": null,
                      "amount": 15000,
                      "createdAt": "2022-10-19T22:34:30.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/users/marketing": {
      "get": {
        "tags": ["Users Marketing"],
        "summary": "get user marketing information",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "discount": {
                    "totalSales": 0,
                    "benefit": 0,
                    "timesUsed": 0,
                    "data": [
                      {
                        "code": "XCKFR353",
                        "type": "percentage",
                        "value": "5",
                        "active": true,
                        "userMarketing": true,
                        "createdAt": "2022-10-19T21:33:07.000Z",
                        "updatedAt": "2022-10-19T21:33:07.000Z"
                      },
                      {
                        "code": "CXBS1HCY",
                        "type": "percentage",
                        "value": "10",
                        "active": true,
                        "userMarketing": true,
                        "createdAt": "2022-10-19T21:33:07.000Z",
                        "updatedAt": "2022-10-19T21:33:07.000Z"
                      }
                    ]
                  },
                  "referral": {
                    "commission": 10,
                    "slug": "ref=24",
                    "sellCount": 0,
                    "viewCount": 0,
                    "totalSale": 0,
                    "benefit": 0,
                    "createdAt": "2022-10-19T21:33:07.000Z",
                    "updatedAt": "2022-10-19T21:33:07.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },

    "/users/transactions": {
      "get": {
        "tags": ["Users Transactions"],
        "summary": "get all user transactions",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 0,
                  "pageSize": 25,
                  "totalCount": 2,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "data": [
                    {
                      "id": 1,
                      "orderId": null,
                      "type": "deposit",
                      "status": "approved",
                      "change": "increase",
                      "amount": 10000,
                      "description": "افزایش موجودی کیف پول",
                      "createdAt": "2022-10-19T22:36:39.000Z",
                      "updatedAt": "2022-10-19T22:36:39.000Z",
                      "deletedAt": null
                    },
                    {
                      "id": 2,
                      "orderId": 3,
                      "type": "order",
                      "status": "approved",
                      "change": "decrease",
                      "amount": 10000,
                      "description": "ثبت سفارش",
                      "createdAt": "2022-10-19T22:36:39.000Z",
                      "updatedAt": "2022-10-19T22:36:39.000Z",
                      "deletedAt": null
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },

    "/users/transactions/id/{id}": {
      "get": {
        "tags": ["Users Transactions"],
        "summary": "get one of user transaction from transaction id",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "orderId": null,
                  "type": "deposit",
                  "status": "approved",
                  "change": "increase",
                  "amount": 10000,
                  "description": "افزایش موجودی کیف پول",
                  "createdAt": "2022-10-19T22:36:39.000Z",
                  "updatedAt": "2022-10-19T22:36:39.000Z",
                  "deletedAt": null
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    }
  },

  "securityDefinitions": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT",
      "in": "header"
    }
  },
  "definitions": {
    "َAffiliates": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" }
      }
    },
    "ContactUs": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "example": "Programmer Kasra" },
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "message": { "type": "string", "example": "Hi,this is a message !" }
      }
    },
    "UsersDeposit": {
      "type": "object",
      "properties": {
        "amount": { "type": "int", "example": 1000 }
      }
    },
    "UsersWithdrawal": {
      "type": "object",
      "properties": {
        "iban": { "type": "string", "example": "123123123123132" },
        "status": {
          "type": "string",
          "example": "This Is A Passowrd!",
          "enum": ["pending", "rejected", "approved", "pending_confirmation"]
        },
        "trackingNumber": { "type": "string", "example": "213124" },
        "amount": { "type": "int", "example": 2000 },
        "description": { "type": "string", "example": "This Is A Description!" }
      }
    },
    "UsersFolders": {
      "type": "object",
      "properties": {
        "color": { "type": "string", "example": "رنگی" },
        "side": { "type": "string", "example": "تک رو" },
        "size": { "type": "string", "example": "A4" },
        "countOfPages": { "type": "int", "example": 6 },
        "uploadedPages": { "type": "int", "example": 2 },
        "binding": { "type": "string", "example": "میخواهم صحافی بشود" },
        "numberOfCopies": { "type": "int", "example": 6 },
        "description": { "type": "string", "example": "این یک توضیح است" },
        "shipmentPrice": { "type": "int", "example": 20000 },
        "amount": { "type": "int", "example": 10000 },
        "files": {
          "type": "array",
          "items": { "type": "int", "example": { "id": 1 } }
        }
      }
    },
    "UsersLogin": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "password": { "type": "string", "example": "This Is A Passowrd!" }
      }
    },
    "UsersOrders": {
      "type": "object",
      "properties": {
        "addressId": { "type": "int", "example": 1 },
        "discountCode": { "type": "string", "example": null },
        "paidWithWallet": { "type": "bool", "example": true },
        "folders": {
          "type": "array",
          "items": { "type": "int", "example": { "id": 1 } }
        }
      }
    },
    "UpdateUsersOrders": {
      "type": "object",
      "properties": {
        "status": { "type": "string", "example": "canceled" },
        "notFinishingReason": { "type": "string", "example": null }
      }
    },
    "UsersProfile": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "example": "Kasra Programmer 2" },
        "password": { "type": "string", "example": "This Is A New Passowrd!" }
      }
    },
    "UsersRegister": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" }
      }
    },
    "UsersRegisterConfirm": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "name": { "type": "string", "example": "Programmer Kasra" },
        "password": { "type": "string", "example": "This Is A Passowrd!" }
      }
    },
    "UsersAddresses": {
      "type": "object",
      "properties": {
        "recipientName": { "type": "string", "example": "کسری تحویل میگیره" },
        "recipientPhoneNumber": {
          "type": "string",
          "example": "09385667274"
        },
        "recipientPostalCode": {
          "type": "string",
          "example": "4675744151"
        },
        "recipientDeliveryProvince": {
          "type": "string",
          "example": "مازندران"
        },
        "recipientDeliveryCity": {
          "type": "string",
          "example": "ساری"
        },
        "recipientDeliveryAddress": {
          "type": "string",
          "example": "خیابان لاله کوچه بهار پلاک دوازده"
        }
      }
    }
  }
}
